# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

language: php

services:
  - mysql
  - postgresql

jobs:
  include:
#    - php: 7.1
#      dist: xenial
#    - php: 7.2
#      dist: xenial
#    - php: 7.3
#      dist: xenial
#    - php: 7.4
#      dist: focal
#    - php: 8.0
#      dist: focal
#    - php: 8.1
#      dist: focal
    - name: "PHP 8.2"
      dist: jammy
      language: ruby # This makes no sence to me, but it works!
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.2 php8.2-mbstring php8.2-cli php8.2-pgsql php8.2-readline php8.2-mcrypt php8.2-gd php8.2-xml php8.2-mysql
        - php -v
        - sudo locale-gen en_US.UTF-8
        - sudo locale-gen cs_CZ.UTF-8
        - sudo update-locale
        - locale -a
        - composer global require "phpunit/phpunit=^7.5" --ignore-platform-reqs
        - ./src/scripts/check_system || echo "FIX REQUIREMENTS!"
        - sudo -u postgres psql -c "CREATE DATABASE test;" -U postgres
        - sudo -u postgres psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'" -U postgres
        - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test" -U postgres
        - sudo mysql -u root -e "USE mysql; UPDATE user SET Grant_priv='Y' WHERE User='root';" # What? root does not have Grant privilege?
        - sudo mysql -u root -e "FLUSH PRIVILEGES;"
        - sudo mysql -u root -e "CREATE DATABASE test;"
        - sudo mysql -u root -e "CREATE USER test@localhost IDENTIFIED BY 'test';"
        - sudo mysql -u root -e "GRANT ALL PRIVILEGES ON test.* TO test@localhost;"
        - sudo mysql -u root -e "FLUSH PRIVILEGES;"
        - sudo apt-get -y install privoxy # privoxy is needed for UrlFetcher testing
        - sudo /etc/init.d/privoxy start || sudo service privoxy start || echo "privoxy failed to start"
        - sudo systemctl status privoxy.service || echo "something failed"
        - sudo journalctl -xe || echo "something failed"

before_install:
  - sudo locale-gen en_US.UTF-8
  - sudo locale-gen cs_CZ.UTF-8
  - sudo update-locale
  - locale -a
  - composer global require "phpunit/phpunit=^7.5" --ignore-platform-reqs
  - ./src/scripts/check_system || echo "FIX REQUIREMENTS!"
  - sudo -u postgres psql -c "CREATE DATABASE test;" -U postgres
  - sudo -u postgres psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'" -U postgres
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test" -U postgres
  - sudo mysql -u root -e "USE mysql; UPDATE user SET Grant_priv='Y' WHERE User='root';" # What? root does not have Grant privilege?
  - sudo mysql -u root -e "FLUSH PRIVILEGES;"
  - sudo mysql -u root -e "CREATE DATABASE test;"
  - sudo mysql -u root -e "CREATE USER test@localhost IDENTIFIED BY 'test';"
  - sudo mysql -u root -e "GRANT ALL PRIVILEGES ON test.* TO test@localhost;"
  - sudo mysql -u root -e "FLUSH PRIVILEGES;"
  - sudo apt-get install privoxy # privoxy is needed for UrlFetcher testing
  - sudo /etc/init.d/privoxy start


script:
  - ./src/scripts/run_all_tests_on_atk14 && echo "EVERYTHING IS FINE"
