# vim:ts=2:sw=2:et
language: php

services:
  - mysql
  - postgresql

php:
  - 5.5

before_install:
  - sudo apt-get update && travis_retry sudo apt-get --reinstall install -qq language-pack-cs
  - locale -a
  - sudo apt-get install php-pear

before_script:
  - phpenv rehash
  - pear config-set auto_discover 1
  - pear config-show
  - sudo pear config-show
  - pear install --alldeps PHPUnit2
  - sudo pear install --alldeps PHPUnit2
  - pear list
  - ls -la /home/travis/.phpenv/versions/5.5.31/share/pear/
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test" -U postgres
  - mysql -e "CREATE DATABASE test;" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost' IDENTIFIED BY 'test';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'127.0.0.1' IDENTIFIED BY 'test';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'::1' IDENTIFIED BY 'test';" -uroot

script:
  - ./src/scripts/run_all_tests_on_atk14 && echo "EVERYTHING IS FINE"
