# vim:ts=2:sw=2:et
language: php

services:
  - mysql
  - postgresql

php:
  - 5.5
  - 5.6

before_install:
  - sudo apt-get update && travis_retry sudo apt-get --reinstall install -qq language-pack-cs
  - locale -a

before_script:
  - pear install --alldeps PHPUnit2
  - psql -c "CREATE DATABASE test ENCODING;" -U postgres
  - psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test" -U postgres
  - mysql -e "CREATE DATABASE test;"
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost' IDENTIFIED BY 'test';";
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'127.0.0.1' IDENTIFIED BY 'test';";
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'::1' IDENTIFIED BY 'test';";

script:
  - ./src/scripts/run_all_tests_on_atk14
