# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
#arch: ppc64le
# ... but on the ppc64le, testing in PHP5.4 and PHP5.5 is not possible
arch: amd64

dist: precise

language: php

services:
  - mysql
  - postgresql

addons:
  postgresql: "9.6"

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - sudo locale-gen en_US.UTF-8
  - sudo locale-gen cs_CZ.UTF-8
  - sudo update-locale
  - locale -a
  - composer global require "phpunit/phpunit=~4.8|~5.7|~6.0"
  - ./src/scripts/check_system || echo "FIX REQUIREMENTS!"
  - sudo service postgresql restart # What? Postgresql is not running?
  - sudo -u postgres psql -c "CREATE DATABASE test;" -U postgres
  - sudo -u postgres psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'" -U postgres
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test" -U postgres
  - sudo mysql -u root -e "USE mysql; UPDATE user SET Grant_priv='Y' WHERE User='root';" # What? root does not have Grant privilege?
  - sudo mysql -u root -e "FLUSH PRIVILEGES;"
  - sudo mysql -u root -e "CREATE DATABASE test;"
  - sudo mysql -u root -e "CREATE USER test@localhost IDENTIFIED BY 'test';"
  - sudo mysql -u root -e "GRANT ALL PRIVILEGES ON test.* TO test@localhost;"
  - sudo mysql -u root -e "FLUSH PRIVILEGES;"

script:
  - ./src/scripts/run_all_tests_on_atk14 && echo "EVERYTHING IS FINE"
