# vim:ts=2:sw=2:et
dist: trusty

language: php

services:
  - mysql
  - postgresql

addons:
  postgresql: "9.6"

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - echo 'en_US.UTF-8 UTF-8' | sudo tee --append /var/lib/locales/supported.d/local
  - echo 'cs_CZ.UTF-8 UTF-8' | sudo tee --append /var/lib/locales/supported.d/local
  - sudo locale-gen
  - locale -a
  - composer global require "phpunit/phpunit=~4.8|~5.7|~6.0"
  - ./src/scripts/check_system || echo "FIX REQUIREMENTS!"

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test" -U postgres
  - mysql -e "CREATE DATABASE test;" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost' IDENTIFIED BY 'test';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'127.0.0.1' IDENTIFIED BY 'test';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'::1' IDENTIFIED BY 'test';" -uroot

script:
  - ./src/scripts/run_all_tests_on_atk14 && echo "EVERYTHING IS FINE"
