#!/usr/bin/env php
<?php
/**
 * Displays environment.
 *
 *  $ ./scripts/_atk14_env
 *  DEVELOPMENT
 *
 *  $ ATK14_ENV=production ./scripts/_atk14_env
 *  PRODUCTION
 */

require_once(dirname(__FILE__)."/load.php");

echo $ATK14_GLOBAL->getEnvironment();
echo "\n";
