#!/usr/bin/env php
<?php
/**
 * Displays environment.
 *
 *  $ ./scripts/_atk14_env
 *  DEVELOPMENT
 *
 *  $ ATK14_ENV=production ./scripts/_atk14_env
 *  PRODUCTION
 *
 *  $ ./scripts/_atk14_env -l
 *	development
 */

define("ATK14_LOAD_AFTER_INITIALIZE_SETTINGS",false);
require_once(dirname(__FILE__)."/load.php");

$env = $ATK14_GLOBAL->getEnvironment();

if(isset($argv[1]) && $argv[1]=='-l'){
	$env = strtolower($env);
}

echo $env;
echo "\n";
