#!/usr/bin/env php
<?php

define("ATK14_LOAD_AFTER_INITIALIZE_SETTINGS",false);
require_once(dirname(__FILE__)."/load.php");

if( isset($argv[1]) && $argv[1] == '--gui' ) {
	$gui = true;
	array_splice($argv, 1, 1);
	$argc-= 1;
} else {
	$gui = false;
}

$configuration_name = isset($argv[1]) ? $argv[1] : "default";

$d = $ATK14_GLOBAL->getDatabaseConfig($configuration_name);

if(!$d){
	exit(1);
}

switch($d["adapter"]){
	case "postgresql":
		$host = $host_gui = $port = $port_gui = "";
		if($d["host"]){
			$host = " -h $d[host]";
			$port = " -p $d[port]";
			$host_gui = " host=$d[host]";
			$port_gui = " port=$d[port]";
		}
		if( $gui ) {
			$cmd = "pgadmin3 -qc 'dbname=$d[database] user=$d[username]$host_gui$port_gui'";
		} else {
			$cmd = "psql -U $d[username] $d[database]$host$port";
		}
		break;
	case "mysql":
		$cmd = "mysql --user=$d[username] --host=$d[host] --port=$d[port] --host=$d[host] --password=$d[password] $d[database]";
		break;
	default:
		exit(1);
}

echo $cmd;
echo "\n";
