#!/usr/bin/env php
<?php

define("ATK14_LOAD_AFTER_INITIALIZE_SETTINGS",false);
require_once(dirname(__FILE__)."/load.php");
require_once(dirname(__FILE__)."/__dump_db_utils.php");

echo dump_db_command("data"),"\n";
