#!/usr/bin/env php
<?php

require_once(dirname(__FILE__)."/load.php");

array_shift($argv); // removing script name

$d = $ATK14_GLOBAL->getDatabaseConfig();

$cmd = "pg_dump -U $d[username] $d[database] -h $d[host] -p $d[port]".($argv ? " ".join(" ",$argv) : "");

echo $cmd,"\n";
