#!/usr/bin/env php
<?php

define("ATK14_LOAD_AFTER_INITIALIZE_SETTINGS",false);
require_once(dirname(__FILE__)."/load.php");

$configurations = array();

foreach(array_keys($ATK14_GLOBAL->getConfig("database")) as $c_name){
	if(in_array($c_name,array("development","test","production"))){
		$c_name = "default";
	}else{
		$c_name = preg_replace('/_(development|test|production)$/','',$c_name);
	}

	if(in_array($c_name,$configurations)){ continue; }
	$configurations[] = $c_name;

	echo $c_name, "\n";
}

