#!/usr/bin/env php
<?php

require_once(dirname(__FILE__)."/load.php");

array_shift($argv); // command _shell_command

$stages = Atk14DeploymentStage::GetStages();

if(!$stages){
	echo 'echo In the config/deploy.yml there are no deployment stages',"\n";
	exit;
}

$stage = "";
$ssh_argv = array();
$shell_argv = array();

while(strlen($_p = array_shift($argv))){
	if(!$stage && !$shell_argv && isset($stages[strtolower($_p)])){
		$stage = strtolower($_p);
		continue;
	}
	if(!$shell_argv && preg_match('/^-/',$_p)){
		$ssh_argv[] = $_p;
	}else{
		$shell_argv[] = $_p;
	}
}

if(!$stage){
	$_keys = array_keys($stages);
	$stage = $_keys[0]; // the first stage
}

if(!isset($stages[$stage])){
	echo sprintf('echo Unknown deploy stage "%s"',$stage),"\n";
	exit;
}

$stage = $stages[$stage];

$s = $stage->toArray();

$port = $s["port"] ? " -p $s[port]" : "";

$cmd = "ssh $s[user]@$s[server]$port";

if(!$shell_argv){
	$shell_argv[] = '$SHELL --login';
	if(!in_array('-t',$ssh_argv)){
		$ssh_argv[] = '-t'; // force pseudo-terminal allocation
	}
}

$cmd .= ($shell_argv ? " " : "").join(" ",$ssh_argv)." cd '$s[directory]' && export ATK14_ENV=production && (".join(" ",$shell_argv).")";

echo $cmd,"\n";
