#!/usr/bin/env php
<?php
define("ATK14_LOAD_AFTER_INITIALIZE_SETTINGS",false);
require_once(dirname(__FILE__)."/load.php");

$remote_host = Atk14Utils::ShellRemoteHost();
if($remote_host){
	echo $remote_host,"\n";
}
