#!/usr/bin/env php
<?php

define("ATK14_LOAD_AFTER_INITIALIZE_SETTINGS",false);
require_once(dirname(__FILE__)."/load.php");

array_shift($argv); // command _shell_command

$stages = Atk14DeploymentStage::GetStages();

if(!$stages){
	echo 'echo In the config/deploy.yml there are no deployment stages',"\n";
	exit;
}

$stage = "";
$ssh_argv = array();
$shell_argv = array();

while(strlen($_p = array_shift($argv))){
	if(!$stage && !$shell_argv && isset($stages[strtolower($_p)])){
		$stage = strtolower($_p);
		continue;
	}
	if(!$stage){
		$ssh_argv[] = $_p;
	}else{
		$shell_argv[] = $_p;
	}
}

if(!$stage && !$ssh_argv){
	$_keys = array_keys($stages);
	$stage = $_keys[0]; // the first stage
}

if($stage==""){
	echo sprintf('echo No stage specified'),"\n";
	exit;
}

if(!isset($stages[$stage])){
	echo sprintf('echo Unknown deploy stage "%s"',$stage),"\n";
	exit;
}

$stage = $stages[$stage];

$s = $stage->toArray();

if(isset($s["port"])){
	$ssh_argv[] = "-p $s[port]";
}

if(!$shell_argv){
	$shell_argv[] = '$SHELL --login';
	if(!in_array('-t',$ssh_argv)){
		$ssh_argv[] = '-t'; // force pseudo-terminal allocation
	}
}

$ssh_options = $ssh_argv ? " ".join(" ",$ssh_argv) : "";

$user = $s["user"] ? "$s[user]@" : "";
$cmd = "ssh$ssh_options $user$s[server]";

$_cmd = "cd '$s[directory]' && export ATK14_ENV=production && (".join(" ",$shell_argv).")";
//$_cmd = strtr($_cmd,array(
//	'"' => '\"',
//));

$cmd .= " $_cmd";

echo $cmd,"\n";
