#!/usr/bin/env bash

# This script checks the host system and installation of the current application

cd $(dirname $0)
exit_val=0

# At first we need run script for checking the system
echo "################"
echo "# checking basic system requirements"
./check_system
if [ "$?" != "0" ]; then
	exit_val=1
fi

# Second, check requirements described in config/requirements.yml (if exists)
echo "################"
echo "# checking application requirements specified in config/requirements.yml"
./_check_requirements
if [ "$?" != "0" ]; then
	exit_val=1
fi

echo "################"
echo "# checking directories"
ROOT=$(./_get_application_path)../
# checking for tmp and log directories
for i in "tmp" "log"; do
	dir="$ROOT$i"
	echo -n "directory $i exists... "
	if [ ! -d $dir ]; then
		echo "fail"
		echo "!!  do the following:"
		echo "!!  $ mkdir -m 0757 $dir"
		exit_val=1
	else	
		echo "ok"
	fi
	# TODO: directory must be writable for others (webserver user)
done

echo "################"
echo "# checking hostname"
http_host=$(./dump_settings ATK14_HTTP_HOST)
echo -n "host $http_host should be resolved... "
etc_hosts_lines=$(egrep "^\s*[0-9a-fA-F\.:][^#]*\s$http_host(|#.*|\s.*)$" /etc/hosts | wc -l)
if [ "$etc_hosts_lines" -eq "0" ]; then
	if [ "$(host $http_host | grep 'not found' | wc -l)" -eq 1 ]; then
		echo "fail"
		echo "!!  there is neither record for $http_host in /etc/hosts nor $http_host could be resolved"
		echo "!!  you may do the following:"
		echo "!!  $ echo '127.0.0.1 $http_host' | sudo tee --append /etc/hosts > /dev/null"
		exit_val=1
	else
		echo "ok"
	fi
else
	echo "ok"
fi

if [ "$exit_val" = "0" ]; then
	echo "Everything seems to be ok"
else
	echo "Something went wrong"
fi

exit $exit_val
