#!/usr/bin/env php
<?php
/**
 * Compiles all templates in app/views/ and app/layouts/
 * This is a useful test to check out that you have all templates compilable.
 *
 * If everyting goes right, you'll see a text TEMPLATES ARE OK
 *
 * Note that this script works with Smarty3 only.
 */

require_once(dirname(__FILE__)."/load.php");
chdir(ATK14_DOCUMENT_ROOT);

function my_exit(){
	global $templates_are_ok;

	if($templates_are_ok){
		echo "\nTEMPLATES ARE OK\n";
		exit(0);
	}else{
		echo "\n!!!THERE ARE COMPILE ERRORS!!!\n";
		exit(1);
	}
}
register_shutdown_function("my_exit"); // there is exit() in $smarty->compileAllTemplates()

$path = $ATK14_GLOBAL->getApplicationPath();
$smarty = Atk14Utils::GetSmarty(
	array(
		"${path}views/",
		"${path}layouts/"
	),
	array("compile_id_salt" => "CompileAllTest")
);

try{
	$templates_are_ok = false;
	$stat = $smarty->compileAllTemplates(".tpl",true,null,1);
	$templates_are_ok = true;
}catch(Exception $e){
	exit(1);
}

exit(0);
