#!/usr/bin/env bash

# An interactive ATK14 console.
# Acts like an Ruby on Rail console.

echo "**************************************************************************"
echo "**                                                                      **"
echo "**               Welcome to ATK14 interactive console                   **"
echo "**                                                                      **"
echo "**************************************************************************"

dir=`dirname $0`
ATK14_DOCUMENT_ROOT=`$dir/dump_settings ATK14_DOCUMENT_ROOT`
cd $ATK14_DOCUMENT_ROOT

#appname=`./scripts/_shell_safe_appname`
#echo -ne "\033]0;ATK14 console for $appname\007"

php -a --php-ini "./scripts/_console/php.ini"
