#!/usr/bin/env bash

# An interactive ATK14 console.
# Acts like an Ruby on Rail console.
#
#  $ ./scripts/console
#
#
# Acts also as a non-interactive console:
#
#  $ echo '$u = User::FindFirst(); var_dump($u->toArray());' | ./scripts/console
#

if [ -t 0 ]; then
	# STDIN is attached to TTY
	echo "**************************************************************************"
	echo "**                                                                      **"
	echo "**               Welcome to ATK14 interactive console                   **"
	echo "**                                                                      **"
	echo "**************************************************************************"
fi

dir=`dirname $0`
ATK14_DOCUMENT_ROOT=`$dir/dump_settings ATK14_DOCUMENT_ROOT`
cd $ATK14_DOCUMENT_ROOT

#appname=`./scripts/_shell_safe_appname`
#echo -ne "\033]0;ATK14 console for $appname\007"

if [ -t 0 ]; then
	# STDIN is attached to TTY
	exec php -a --php-ini "./scripts/_console/php.ini"
else
	# STDIN is attached to a pipe
	# An opening php tag needs to be added before the content of the STDIN
	(echo -n '<?php ' && cat) | exec php --php-ini "./scripts/_console/php.ini"
fi
