#!/usr/bin/env bash

# create a database and an database user according to config/database.yml

dirname=`dirname $0`;
cd $dirname;

PG_USER=postgres                          # Postgresql's service account name
DBNAME=`./_database_username`
DBPASSWORD=`./_database_password`
ENVIRONMENT=`./_atk14_env`
ENCODING=`./dump_settings DEFAULT_CHARSET`
environment=`echo -n  $ENVIRONMENT | tr A-Z a-z`

# ENCODING is being added only for UTF8
sql_encoding=""
#if [ "$ENCODING" = "UTF-8" ]; then
#	sql_encoding=" WITH ENCODING 'UTF8'"
#fi
# TODO: It doesn't work. It says:
# ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
# HINT:  Use the same encoding as in the template database, or use template0 as template.

sql=$( cat <<EOF
-- creating database for $ENVIRONMENT
CREATE DATABASE $DBNAME$sql_encoding;
CREATE USER $DBNAME WITH ENCRYPTED PASSWORD '$DBPASSWORD';
EOF
)
if [ "$1" != '-f' ] ; then

echo "Gonna execute the following SQL as user $PG_USER in database template1:"
echo ""
echo "$sql"
echo ""
echo "Your system password may be requested due to sudo usage"
echo -n "Are you happy with that? (press y if so) "
read confirm
if [ "$confirm" != "y" ]; then
  exit 1
fi

fi

echo "$sql" | sudo -u $PG_USER -s psql template1 || exit 1

if [ "$1" != '-f' ] ; then

echo
echo "Now you may want to run"
#echo "  $ touch ~/.pgpass && chmod 600 ~/.pgpass && ATK14_ENV=$environment $dirname/pgpass_record >> ~/.pgpass" # this is gonna be made automatically
echo "  $ ATK14_ENV=$environment $dirname/migrate"
echo
echo "At any time you can enter database console by typing"
echo "  $ ATK14_ENV=$environment $dirname/dbconsole"

fi
