#!/usr/bin/env bash

# create a database and an database user according to config/database.yml

dirname=`dirname $0`;
cd $dirname;

PG_USER=postgres                          # Postgresql's service account name
DBUSER=`./_database_username`
DBNAME=`./_database_database`
DBPASSWORD=`./_database_password`
ENVIRONMENT=`./_atk14_env`
CREATE_DATABASE_COMMAND=`./_create_database_command`
environment=`echo -n  $ENVIRONMENT | tr A-Z a-z`

sql=$( cat <<EOF
-- creating database for $ENVIRONMENT
$CREATE_DATABASE_COMMAND
CREATE USER $DBUSER WITH ENCRYPTED PASSWORD '$DBPASSWORD';
GRANT ALL PRIVILEGES ON DATABASE $DBNAME TO $DBUSER;
EOF
)
if [ "$1" != '-f' ] ; then

echo "Gonna execute the following SQL as user $PG_USER in database template1:"
echo ""
echo "$sql"
echo ""
echo "Your system password may be requested due to sudo usage"
echo -n "Are you happy with that? (press y if so) "
read confirm
if [ "$confirm" != "y" ]; then
  exit 1
fi

fi

echo "$sql" | sudo -u $PG_USER -s psql template1 || exit 1

if [ "$1" != '-f' ] ; then

echo
echo "Now you may want to run"
#echo "  $ touch ~/.pgpass && chmod 600 ~/.pgpass && ATK14_ENV=$environment $dirname/pgpass_record >> ~/.pgpass" # this is gonna be made automatically
echo "  $ ATK14_ENV=$environment $dirname/migrate"
echo
echo "At any time you can enter database console by typing"
echo "  $ ATK14_ENV=$environment $dirname/dbconsole"

fi
