#!/bin/sh

# Starts a database console.
#
#  $ ./scripts/dbconsole
#  $ ./scripts/dbconsole default
#  $ ./scripts/dbconsole import
#  # or
#  $ ATK14_ENV=PRODUCTION ./scripts/dbconsole
#  $ ATK14_ENV=PRODUCTION ./scripts/dbconsole default
#  $ ATK14_ENV=PRODUCTION ./scripts/dbconsole import

cd `dirname $0`

# add pgpass record to ~/.pgpass file when the record is not present
exec `./pgpass_record -a`

configuration_name=$1 # e.g. default, import, see Atk14Global::getDatabaseConfig()

cmd=`./_dbconsole_command "$configuration_name"`
if [ "$cmd" = "" ]; then
	echo "Sorry bro, I don't know how to connect to the $configuration_name";
	exit 1
fi
exec $cmd
