#!/bin/sh

# Dumps database data and/or schema.
# May be useful for backup.
#
#  $ ./scripts/dump_data
#  $ ATK14_ENV=PRODUCTION ./scripts/dump_db

[ $# -gt 1 ] && echo "Wrong number of arguments" && exit 1;
[ $# -eq 0 ] && ARG="all" || ARG="$1"

cd `dirname $0`

case "$ARG" in
	"data")
		cmnd="./_dump_dbdata_command"
		exec `$cmnd`
		;;
	"schema")
		cmnd="./_dump_dbschema_command"
		exec `$cmnd`
		;;
	"all")
		cmnd="./_dump_dbschema_command"
		exec `$cmnd` | cat
		echo "hello" >&2
		cmnd="./_dump_dbdata_command"
		exec `$cmnd` | cat
		;;
	"help")
		echo "\nDumps database data, schema or both\n"
		echo "$0 [data|schema|all]\n"
		;;
	*)
		echo "Parameter '$ARG' not recognized\n"
		exit 1;
		;;
esac

exit 0;
