#!/bin/sh

# Dumps database data and/or schema.
# May be useful for backup.
#
#  $ ./scripts/dump_db
#  $ ATK14_ENV=PRODUCTION ./scripts/dump_db
#
# To dump schema and data from a specific table:
#
#  $ ATK14_ENV=PRODUCTION ./scripts/dump_db -t users

cd $(dirname $0)

# add pgpass record to ~/.pgpass file when the record is not present
exec $(./pgpass_record -a)

cmd=$(./_dump_db_command "$@")
exec $cmd
