#!/usr/bin/env php
<?php
/**
* Dumps configuration constants.
*
* You can check out how configuration varies in different environments.
*
*  $ ATK14_ENV=PRODUCTION ./scripts/dump_settings
*  $ ATK14_ENV=DEVELOPMENT ./scripts/dump_settings
*  $ ATK14_ENV=TEST ./scripts/dump_settings
*
* Also you can retrieve the value of the given constant:
*  $ ./scripts/dump_settings ATK14_APPLICATION_NAME
*
* Exporting data in json format
*  $ ./scripts/dump_settings --json
*  $ ./scripts/dump_settings -j
*  $ ./scripts/dump_settings --json ATK14_APPLICATION_NAME
*  $ ./scripts/dump_settings -j ATK14_APPLICATION_NAME
*/

require_once(dirname(__FILE__)."/load.php");

function _exit_with_error($message){
	$stderr = fopen('php://stderr', 'w');
	fwrite($stderr,"$message\n");
	exit(1);
}

$constants = array_merge(array(
	"DEVELOPMENT" => DEVELOPMENT,
	"PRODUCTION" => PRODUCTION,
	"TEST" => TEST,
),$__CONFIG_CONSTANTS__);

$spec_constant = null;
$json = false;

$command = array_shift($argv);
foreach($argv as $a){
	if(preg_match('/^[A-Z]/',$a)){ $spec_constant = $a; }
	elseif(preg_match('/^(-j|--json)$/',$a)){ $json = true; }
	else{
		_exit_with_error("Unknown option $a");
	}
}

if(isset($spec_constant) && !isset($constants[$spec_constant]) && defined($spec_constant)){
	$constants[$spec_constant] = constant($spec_constant); 
}

if($json){
	if($spec_constant){
		$ary = isset($constants[$spec_constant]) ? array($spec_constant => $constants[$spec_constant]) : array();
	}else{
		$ary = $constants;
	}

	foreach($ary as $k => $v){
		if(is_string($v) && !Translate::CheckEncoding($v,"UTF-8")){
			$v = Translate::Trans($v,DEFAULT_CHARSET,"UTF-8");
			if(!Translate::CheckEncoding($v,"UTF-8")){
				_exit_with_error("Invalid charset in $k=$v");
			}
			$ary[$k] = $v;
		}
	}

	echo json_encode($ary,JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE), "\n";
	exit(0);
}

foreach($constants as &$c){	if(is_bool($c)){ $c = $c ? "true" : "false"; } }

if(isset($spec_constant)){
	if(!isset($constants[$spec_constant])){
		_exit_with_error("There is no constant $spec_constant");
	}

	echo $constants[$spec_constant]."\n";
	exit;
}

print_r($constants);
