#!/bin/sh

# Dumps database schema.
#
#  $ ./scripts/dump_dbschema
#  $ ATK14_ENV=PRODUCTION ./scripts/dump_dbschema

cd `dirname $0`

# add pgpass record to ~/.pgpass file when the record is not present
exec `./pgpass_record -a`

cmd=`./_dump_dbschema_command`
exec $cmd
