#!/usr/bin/env php
<?php
/**
 * Generates Atk14 framework documentation.
 *
 * Just run ./generate_documentation.php
 *
 * By default the script generates only framework documentation
 * but can also document an application using Atk14.
 *
 * Add -a or -app flag to also generate documentation of application.
 * Flag -nf or --noframework disables the framework documentation generation.
 *
 * Requires PhpDocumentor
 *
 * You can install it with pear.
 * pear install PhpDocumentor.
 *
 * More info about PhpDocumentor is available at http://phpdoc.org/
 *
 */

require_once(dirname(__FILE__)."/load.inc");

$output_dir = realpath($ATK14_GLOBAL->getApplicationPath()."../tmp/documentation");

$src_dirs = array();
$options = array(
	"generate_fw_doc" => true,
	"generate_app_doc" => false,
);
$switches = array(
	"--defaultpackagename" => "Atk14",

	"--title" => "'Atk14 Documentation'",
	"--extensions" => "php,inc",

	// ignored files
	"--ignore" => array(
		"*/test/*.inc",
		"*/test/*.php",
		"tc_*.php",
		"tc_*.inc",
		"*/load.inc",
		"*/load.php",
		"initialize.inc",
		"*/demo/*",
	),
	"--directory" => array(
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/atk14",
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/dbmole",
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/dictionary",
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/files",
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/forms",
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/http",
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/logger",
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/string",
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/stringbuffer",
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/tablerecord",
		$ATK14_GLOBAL->getApplicationPath()."../atk14/src/xmole",
	),

	"--target" => "$output_dir",
);

// framework is documented by default
$_args = array_merge($argv, array("-f"));

if (isset($_args)) {
	foreach($_args as $arg) {
		switch($arg) {
		case "-a":
		case "-app":
			$options["generate_app_doc"] = true;
			break;
		case "-nf":
		case "-noframework":
			$options["generate_fw_doc"] = false;
			break;
		}
	}
}

if (!$options["generate_fw_doc"]) {
	$switches["--directory"] = array();
}

if ($options["generate_app_doc"]) {
	$switches["--directory"][] = $ATK14_GLOBAL->getApplicationPath()."/models";
	$switches["--packageoutput"][] = "ApplicationDoc";
	$switches["--defaultpackagename"] = "ApplicationDoc";
	$switches["--title"] = "'Application Documentation'";
}


if (!file_exists($output_dir)) {
	files::mkdir($output_dir, &$err, &$err_str);
}

$src_dir = join(",", $src_dirs);

$prms = "";
foreach($switches as $sw => $val) {
	if (is_array($val)) {
		$val = implode(",", $val);
	}
	if (strlen(trim($val))>0) {
		$prms .= " $sw $val";
	}
}

$command = sprintf("phpdoc  %s", $prms);

$val = system($command, $ret);

if ($ret == 127) {
	echo "\nPhpDocumentor tool not found\n\n";
	echo "Please check that you have installed PhpDocumentor and you have phpdoc command in \$PATH\n";
	echo "If you don't have PhpDocumentor install it from http://phpdoc.org/ and try again.\n\n";
	exit(2);
}




