#!/usr/bin/env php
<?php
/**
* Initializes database! :)
* Creates all necessaries in there.
*
* At the moment, it creates only the table schema_migrations.
*
* Usage:
*  $ ATK14_ENV=DEVELOPMENT ./scripts/initialize_database
*  $ ATK14_ENV=TEST ./scripts/initialize_database
*/

require_once(dirname(__FILE__)."/load.php");

$dbmole->doQuery("CREATE TABLE schema_migrations(
	version VARCHAR(255) PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT NOW()
)");

