#!/usr/bin/env php
<?php
/**
* Initializes database! :)
* Creates all necessaries in there.
*
* At the moment, it creates only the table schema_migrations.
*
* Usage:
*  $ ATK14_ENV=DEVELOPMENT ./scripts/initialize_database
*  $ ATK14_ENV=TEST ./scripts/initialize_database
*/

require_once(dirname(__FILE__)."/load.php");

if(Atk14Migration::SchemaMigrationsTableExists($dbmole)){
	echo "It seems the database has been already initialized\n";
	exit(1);
}

Atk14Migration::CreateSchemaMigrationsTable($dbmole);
exit(0);
