#!/usr/bin/env php
<?php
/**
 * $ ./scripts/robot_runner import_articles
 * $ ./scripts/robot_runner import_articles_robot
 * $ ./scripts/robot_runner ImportArticles
 * $ ./scripts/robot_runner ImportArticlesRobot
 */

require_once(dirname(__FILE__)."/load.php");

ini_set("log_errors","On");
ini_set("error_log",LOG_DIR."/robots_error.log");

$robots_dir = $ATK14_GLOBAL->getApplicationPath()."/../robots";

$robot_name = null;

$arguments = getopt("",array("robot::"));
if(isset($arguments["robot"])){
	$robot_name = $arguments["robot"];
}

if(!$robot_name && isset($argv[1])){
	$robot_name = $argv[1];
}

if(strlen($robot_name)){
	// ImportUserRobot -> import_user
	// import_user_robot.php -> import_user
	// robots/import_user_robot.php -> import_user
	$robot_name = String4::ToObject($robot_name)->underscore()->gsub('/_robot(\.php|\.inc|)$/','')->gsub('/^.+\/([^\/]+)$/','\1');
}

if(!$robot_name){
	echo "This script executes a robot.\n";
	echo "You can run a given robot by calling:\n";
	echo "$ $argv[0] robot_name\n";
	echo "# or\n";
	echo "$ $argv[0] --robot=robot_name\n\n";
	echo "Default robot log file is log/robots.log\n";
	echo "Usually robots create lock files in ".LOCK_DIR."\n";
	// print help message and exit
	echo "\n";

	$robots = array();
	$dir = opendir($robots_dir);
	while($item = readdir($dir)){
		if(!preg_match('/^([a-z0-9_]+)_robot\.php$/',$item,$matches)){ continue; }
		if($matches[1]=="application"){ continue; }
		$robots[] = $matches[1];
	}
	asort($robots); // !! it keeps indexes
	$robots = array_values($robots);

	if(!$robots){
		echo "In this application there is no robot\n";
	}else{
		echo "In this application there are following robots:\n";
		foreach($robots as $i => $robot){
			echo ($i+1).") $robot\n";
		}

		if(posix_isatty(STDOUT) && posix_isatty(STDIN)){
			echo "Enter number or name of the robot to be executed\n";
			echo "number> ";

			$fh = fopen('php://stdin', 'r');
			$no = trim(fgets($fh,1024));
			if(is_numeric($no) && isset($robots[$no-1])){
				$robot_name = String4::ToObject($robots[$no-1]);
			}elseif(in_array($no,$robots)){
				$robot_name = String4::ToObject($no);
			}elseif(strlen($no)){
				echo "Fatal: unknown robot\n";
			}
		}
	}
	
	if(!$robot_name){
		exit(1);
	}
}

if(!file_exists("$robots_dir/{$robot_name}_robot.php")){
	echo "Fatal: robot $robot_name doesn't exist\n";
	exit(1);
}

require_once("$robots_dir/application_robot.php");
require_once("$robots_dir/{$robot_name}_robot.php");

$class_name = $robot_name->camelize()."Robot"; // ImportUserRobot
$robot = new $class_name();
$robot->__runRobot();
