#!/usr/bin/env bash
#
# This scripts performs all tests on the framework
#
# $ ./scripts/run_all_tests_on_atk14
# $ PHP_BIN=/path/to/php7 ./scripts/run_all_tests_on_atk14

dirname=$(dirname $0)
cd $dirname
base_dir=$(pwd -P)
cd $base_dir
cd ../..

if [ "x$PHP_BIN" = "x" ]; then
	PHP_BIN=$(which php)
fi

ret=0
for dir in $(find ./ -type d -name test | sort); do
	# in a directory with tests there should be initialize.php (or initialize.inc)
	if [ -e $dir/initialize.php ] || [ -e $dir/initialize.inc ]; then
		echo
		echo
		echo "###### $dir"
		$PHP_BIN $base_dir/run_unit_tests $dir/
		last_ret_code=$?
		if [ $last_ret_code -ne 0 ]; then
			ret=$last_ret_code
		fi
	fi
done

echo ""
if [ "$ret" = "1" ]; then
	echo "There were errors"
else
	echo "Everything looks fine"
fi

exit $ret
