#!/usr/bin/env php
<?php
/*
* V pracovnim adresari vyhleda soubory tc_*.inc. Ty postupne nainkluduje a spusti v nich testy.
*
* V souboru tc_currency.inc se ocekava trida TcCurrency, prip. tc_currency.
*
* Na prikazove radce mozno definovat seznam testu, ktere se maji provest:
*		$ run_unit_tests tc_account tc_bank_transfer
*		pripadne i s priponou .php
*		$ run_unit_tests tc_account.php tc_bank_transfer.php
*
* Nebezpecne testy
* ----------------
* Jsou to takove testy, ktere zmeni/nastavi neco, co muze mit nejake nasledky. Napriklad testy pro registraci domeny.
* Takove testy umistime do souboru zacinajici vykricnikem, napr. !tc_domain_registration.php
*
* Test nebude automaticky spusten, pokud nebude implicitne uveden na prikazove radce:
*		$ run_unit_tests
*		$ run_unit_tests \!tc_domain_registration.php
*/

error_reporting(255);

// v PHP5.3 neexistuje $_ENV["PWD"] ??
isset($_ENV["PWD"]) && chdir($_ENV["PWD"]);

if(preg_match("/^4/",phpversion())){
	define("PHP4",true);
	define("PHP5",false);
}
if(preg_match("/^5/",phpversion())){
	define("PHP4",false);
	define("PHP5",true);
}

if(PHP4){
	include_once 'PHPUnit.php';
	if(!class_exists("PHPUnit_TestCase")){
		echo "Missing dependency: class PHPUnit_TestCase\n";
		echo "The following command may help you\n";
		echo "\n";
		echo " $ sudo pear install PHPUnit\n";
		echo "\n";
		exit(1);
	}
}
if(PHP5){
	include_once 'PHPUnit2/Framework/TestSuite.php';
	include_once 'PHPUnit2/Framework/TestCase.php';
	include_once 'PHPUnit2/TextUI/ResultPrinter.php';
	include_once 'Benchmark/Timer.php';

	if(!class_exists("PHPUnit2_Framework_TestCase")){
		echo "************************************************************\n";
		echo "*  Missing dependency: class PHPUnit2_Framework_TestCase   *\n";
		echo "*  The following command may help you                      *\n";
		echo "*                                                          *\n";
		echo "*  $ sudo pear install --alldeps PHPUnit2                  *\n";
		echo "*                                                          *\n";
		echo "************************************************************\n";
		exit(1);
	}
}

isset($argv) || ($argv = array());

$SCRIPT = array_shift($argv);
$DIR = "";
$RUN_TESTS_ONLY = array();
while($_a = array_shift($argv)){
	if(is_dir($_a)){ $DIR = $_a; continue; }
	$RUN_TESTS_ONLY[] = $_a;
}
if($DIR){
	$DIR = preg_replace('/([^\/])$/','\1/',$DIR);
	chdir($DIR);
}

if(PHP4){
	eval("class tc_super_base extends PHPUnit_TestCase{ }");
	eval("class TcSuperBase extends PHPUnit_TestCase{ }");
}
if(PHP5){
	eval("class tc_super_base extends PHPUnit2_Framework_TestCase{ }");
	eval("class TcSuperBase extends PHPUnit2_Framework_TestCase{ }");
}

if(file_exists($_f = "initialize.inc") || file_exists($_f = "initialize.php")){ require_once($_f); }

if(file_exists($_f = "tc_base.inc") || file_exists($_f = "tc_base.php")){
	require_once($_f);
}else{
	eval("class tc_base extends tc_super_base{ }");
	eval("class TcBase extends TcSuperBase{ }");
}

if(class_exists("pgmole")){	
	$dbmole = &PgMole::GetInstance();
	DbMole::RegisterErrorHandler("_test_dbmole_error_handler");
}
if(class_exists("oraclemole")){
	$dbmole = &OracleMole::GetInstance();
	DbMole::RegisterErrorHandler("_test_dbmole_error_handler");
}
if(class_exists("inobj")){
	inobj::RegisterErrorCallback("_test_inobj_error_handler");
}

$ALLOWED_TESTS = array();
$ALLOWED_DANGEROUS_TESTS = array();
$tests_to_execute = array();

$dir = opendir("./");
while($file = readdir($dir)){
	if(in_array($file,array(".","..","initialize.inc","initialize.php","state.inc","state.php","tc_base.inc","tc_base.php"))){ continue; } // tyto souboryu ignorujeme

	if(preg_match("/^(tc_.*)\\.(inc|php)$/",$file,$matches)){
		$ALLOWED_TESTS[$file] = $matches[1];
	}elseif(preg_match("/^!(tc_.*)\\.(inc|php)$/",$file,$matches)){
		$ALLOWED_DANGEROUS_TESTS[$file] = $matches[1];
	}
}
closedir($dir);

ksort($ALLOWED_TESTS);

reset($ALLOWED_TESTS);
while(list($filename,$classname) = each($ALLOWED_TESTS)){
	if(sizeof($RUN_TESTS_ONLY)>0 && (!in_array($filename,$RUN_TESTS_ONLY) && !in_array($classname,$RUN_TESTS_ONLY))){
		continue;
	}

	//_test_runner($filename);
	$tests_to_execute[] = $filename;
}

reset($ALLOWED_DANGEROUS_TESTS);
while(list($filename,$classname) = each($ALLOWED_DANGEROUS_TESTS)){
	if((!in_array($filename,$RUN_TESTS_ONLY) && !in_array($classname,$RUN_TESTS_ONLY))){
		continue;
	}

	//_test_runner($filename);
	$tests_to_execute[] = $filename;
}

if(sizeof($tests_to_execute)==1){
	_test_runner($tests_to_execute[0],$DIR:);
	exit;
}


foreach($tests_to_execute as $_f){
	$cmd = escapeshellcmd($SCRIPT)." ".escapeshellarg($_f)." 2>&1";
	if(isset($_SERVER["_"])){
		// v $_SERVER["_"] je interpret PHP: /usr/bin/php
		$cmd = escapeshellcmd($_SERVER["_"])." ".escapeshellarg($SCRIPT)." ".escapeshellarg($_f)." 2>&1";
	}
	passthru($cmd);
}

function _test_dbmole_error_handler($dbmole){
	echo "An error comes from DbMole\n";
	echo "database type: ".$dbmole->getDatabaseType()."\n";
	echo "message ".$dbmole->getErrorMessage()."\n";
	echo "query: ".$dbmole->getQuery()."\n";
	echo "bind_ar:\n";
	print_r($dbmole->getBindAr());
	echo "options:\n";
	print_r($dbmole->getOptions());
	exit;
}

function _test_inobj_error_handler($values){
	echo "An error comes from inobj\n";
	print_r($values);
	exit;
}

function _test_runner($filename,$DIR){
	$classname = preg_replace('/\.[^.]*$/',"",$filename);
	$classname = preg_replace('/^!/',"",$classname);
	$alt_classname = preg_replace('/_/',"",$classname);

	require($filename);

	if(class_exists($alt_classname)){ $classname = $alt_classname; }

	if(!class_exists($classname)){
		echo "--- $DIR$filename\n";
		echo "!!! class $classname doesn't exist\n";
		return;
	}

	if(PHP4){
		$suite  = new PHPUnit_TestSuite($classname);
		$result = PHPUnit::run($suite);
		echo "--- $DIR$filename\n";
		print $result->toString();
	}
	if(PHP5){
		$timer  = new Benchmark_Timer;
		$printer = new PHPUnit2_TextUI_ResultPrinter;

		$suite  = new PHPUnit2_Framework_TestSuite(
			new ReflectionClass($classname)
		);

		$timer->start();
		$result = $suite->run();
		$timer->stop();

		echo "--- $DIR$filename\n";
		$printer->printResult($result, $timer->timeElapsed());
	}
}
