#!/usr/bin/env bash

# Stars a webserver for development
#
# By default the server is listening on port 8000
#
# Usage:
#
#		$ ./scripts/server
#
# A different port could be specified as the first parameter:
#
#		$ ./scripts/server 8001

echo "**************************************************************************"
echo "**                                                                      **"
echo "**          This is an experimental web server designed to aid          **"
echo "**                  ATK14 application development.                      **"
echo "**                                                                      **"
echo "**          It is not intended to be a full-featured web server.        **"
echo "**             It should not be used on a public network.               **"
echo "**                                                                      **"
echo "**************************************************************************"

cd `dirname $0`
cd `./_get_application_path`../

port=${1:-8000} # TODO: could be nice to check whether the given port is available
appname=`./scripts/_shell_safe_appname`

echo -ne "\033]0;ATK14 server for $appname - http://localhost:$port/\007"

php -S localhost:$port -t ./ ./scripts/_server.php

