#!/bin/bash

cd `dirname $0` # /home/joe/webapps/myapp/scripts
cd ..           # /home/joe/webapps/myapp

PWD=`pwd`                                       # /home/joe/webapps/myapp
APPNAME=`basename "$PWD" | tr "[A-Z]" "[a-z]"`  # myapp
HOSTNAME="$APPNAME.localhost"                   # myapp.localhost
FORCE=

while [ -n "$1" ] ; do
  case $1 in
    "-f") FORCE=1 ;;
    *) break      ;;
  esac
  shift
done

APACHE_CONF_DIR=
APACHE_CONF_FILENAME="$APPNAME.localhost" # ??? Matyas pridaval ".conf"

APACHE_CONF=`cat <<EOF
  <VirtualHost *:80>
   DocumentRoot $PWD
   ServerName $HOSTNAME
   <Directory $PWD>
    Options FollowSymLinks
    AllowOverride All
    Order deny,allow
    Allow from all
   </Directory>
  </VirtualHost>
EOF`

if [ -z "$FORCE" ]; then
  echo "\
# This is apache virtual host configuration for http://$HOSTNAME/
# You can let this script deploy the configuration automatically by typing the comman bellow.
# Automatic deploy works great on Ubuntu.
#
#   $ $0 -f
# 
# or you can do it manually following the instructions bellow.
#
#   $ $0 | sudo tee /etc/apache2/sites-available/$HOSTNAME > /dev/null
#   $ sudo a2ensite $HOSTNAME
#   $ echo '127.0.0.1 $HOSTNAME' | sudo tee --append /etc/hosts > /dev/null
#
# now reload apache
#   $ sudo service apache2 reload
#    or
#   $ sudo /etc/init.d/apache2 reload
#

$APACHE_CONF
"
  exit 0
fi

echo "Going to deploy apache configuration for $HOSTNAME"

for dir in /etc/apache2/sites-available /etc/apache2/vhosts.d ; do
  if [ -e $dir ] ; then
    APACHE_CONF_DIR="$dir"
    break;
  fi      
done

# configuring apache
echo ""
if [ -z "$APACHE_CONF_DIR" ] ; then 
  echo "WARNING: Apache configuration not found, please configure apache manually!"
else
  APACHE_CONF_FILE="$APACHE_CONF_DIR/$APACHE_CONF_FILENAME"

  echo "About to configure apache for new virtualhost $HOSTNAME"
  echo " in directory $PWD"
  echo " using config file $APACHE_CONF_FILE"

  if [ ! -e  "$APACHE_CONF_FILE" ] ; then
    echo "$APACHE_CONF" | sudo tee "$APACHE_CONF_FILE" > /dev/null

    for dir in /etc/apache2/sites-enabled ; do
      if [ -e $dir ] ; then 
        sudo ln -s $APACHE_CONF_FILE $dir/$APACHE_CONF_FILENAME
        break 
      fi
    done

    # !!! toto nelze, protoze v ubuntu je /etc/apache2/apache2.conf 
    # grep -q '^\s*NameVirtualHost\s*\*\s*:\s*80' /etc/apache2/httpd.conf ||
    # (
    #  echo " Add NamedVirtualHost directive to /etc/apache2/httpd.conf"
    #  echo " NameVirtualHost *:80" | sudo tee --append /etc/apache2/httpd.conf;> /dev/null
    # )

    echo ""
    echo "About to restart apache"
    RESTART=
    for cmd in /etc/init.d/apache2 /usr/sbin/rcapache2 ; do
      if sudo [ -x "$cmd" ] && sudo "$cmd" restart ; then
        RESTART=1
        break  
      fi
    done
    if [ -z "$RESTART" ] ; then
      echo "WARNING: Restarting command not found or failed, please restart apache manually!"     
    fi;
  else
    echo "WARNING: Old configuration file found, it was let intact."
  fi
fi


egrep -q "^[^#]+\s$HOSTNAME" /etc/hosts  || (
  echo ""
  echo "About to add 127.0.0.1 $HOSTNAME record to /etc/hosts"
  echo "
# $HOSTNAME added by atk14_init.sh
127.0.0.1 $HOSTNAME" | sudo tee --append  /etc/hosts > /dev/null
) || exit 1

echo ""
echo "Now try http://$HOSTNAME/ in your browser"
