<?php
define("TEST",true);
setlocale(LC_NUMERIC,"C");
require(__DIR__."/../../../string4/load.php");
require(__DIR__."/../../../translate/load.php");
require(__DIR__."/../function.to_json.php");
require(__DIR__."/../modifier.camelize.php");
require(__DIR__."/../modifier.to_sentence.php");
require(__DIR__."/../modifier.count.php");
require(__DIR__."/../modifier.slugify.php");
require(__DIR__."/../modifier.format_number.php");
require(__DIR__."/../block.javascript_tag.php");
require_once(__DIR__."/../block.no_spam.php");
require_once(__DIR__."/../modifier.no_spam.php");
require_once(__DIR__."/../modifier.strip_tags.php");
require_once(__DIR__."/../block.strip_tags.php");

require(__DIR__."/../../../functions.php");
require(__DIR__."/../block.replace_html.php");
require(__DIR__."/../../atk14_utils.php");
require(__DIR__."/../../atk14_locale.php");
require(__DIR__."/../../atk14_require.php");
