<?php
require_once(dirname(__FILE__)."/itablerecord_databaseccessor.php");
require_once(dirname(__FILE__)."/tablerecord_databaseccessor_postgresql.php");
require_once(dirname(__FILE__)."/tablerecord_databaseccessor_mysql.php");
require_once(dirname(__FILE__)."/tablerecord.php");
require_once(dirname(__FILE__)."/tablerecord.php");
require_once(dirname(__FILE__)."/tablerecord_finder.php");
require_once(dirname(__FILE__)."/tablerecord_emptyfinder.php");
require_once(dirname(__FILE__)."/tablerecord_lister.php");
require_once(dirname(__FILE__)."/cache.php");
