<?php
if(!class_exists("inobj")){
	require_once(__DIR__."/src/inobj.php");
}
require_once(__DIR__."/src/itablerecord_databaseccessor.php");
require_once(__DIR__."/src/tablerecord_databaseccessor_postgresql.php");
require_once(__DIR__."/src/tablerecord_databaseccessor_mysql.php");
require_once(__DIR__."/src/tablerecord_databaseaccessor_sqlsrv.php");
require_once(__DIR__."/src/tablerecord.php");
require_once(__DIR__."/src/tablerecord.php");
require_once(__DIR__."/src/tablerecord_finder.php");
require_once(__DIR__."/src/tablerecord_emptyfinder.php");
require_once(__DIR__."/src/tablerecord_lister.php");
require_once(__DIR__."/src/cache.php");
