<?
require_once(dirname(__FILE__)."/inobj.inc");
require_once(dirname(__FILE__)."/inobj_tablerecord_base.inc");
require_once(dirname(__FILE__)."/inobj_tablerecord.inc");
require_once(dirname(__FILE__)."/inobj_tablerecord_finder.inc");
require_once(dirname(__FILE__)."/inobj_tablerecord_emptyfinder.inc");
require_once(dirname(__FILE__)."/inobj_tablerecord_lister.inc");
require_once(dirname(__FILE__)."/cache.inc");

